"""Regenerate the web subset with: python -m pip install 'fonttools[woff]'."""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "public/fonts/suit/SUIT-Variable.woff2"
characters = set(range(0x20, 0x100))
# Include browser-generated list markers, punctuation and typographic spacing.
characters.update(range(0x2000, 0x2070))
characters.update(range(0x25A0, 0x2600))
for directory in ("app", "components", "lib"):
    for source in (ROOT / directory).rglob("*"):
        if source.suffix in (".ts", ".tsx", ".json", ".css"):
            characters.update(map(ord, source.read_text(encoding="utf-8")))
font = TTFont(FONT)
all_characters = set(font.getBestCmap())
characters &= all_characters
options = subset.Options()
options.layout_features = ["*"]
options.name_IDs = ["*"]
options.name_languages = ["*"]
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=characters)
subsetter.subset(font)
# The upstream license reserves SUIT. Use a distinct internal name for this derivative.
names = {1: "AXONE Web Sans", 2: "Regular", 3: "AXONE Web Sans 1.0", 4: "AXONE Web Sans", 6: "AXONEWebSans-Regular", 16: "AXONE Web Sans", 17: "Regular", 25: "AXONEWebSans"}
for record in font["name"].names:
    if record.nameID in names:
        record.string = names[record.nameID].encode(record.getEncoding())
font.flavor = "woff2"
destination = FONT.with_name("AXONE-Web-Sans.woff2")
font.save(destination)
def ranges(points):
    result = []
    for point in sorted(points):
        if result and result[-1][1] + 1 == point:
            result[-1][1] = point
        else:
            result.append([point, point])
    return ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in result)

unicode_range = ranges(characters)
css = "/* Generated by tooling/subset-font.py; disjoint ranges prevent duplicate downloads. */\n"
css += "@font-face {\n  font-family: 'SUIT Variable';\n  src: url('/fonts/suit/AXONE-Web-Sans.woff2') format('woff2');\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n"
css += f"  unicode-range: {unicode_range};\n}}\n"
css += "@font-face {\n  font-family: 'SUIT Variable';\n  src: url('/fonts/suit/SUIT-Variable.woff2') format('woff2');\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n"
css += f"  unicode-range: {ranges(all_characters - characters)};\n}}\n"
(ROOT / "app/font-subset.css").write_text(css, encoding="utf-8")
assert set(TTFont(destination).getBestCmap()) == characters
assert [(a.axisTag, a.minValue, a.maxValue) for a in TTFont(destination)["fvar"].axes] == [(a.axisTag, a.minValue, a.maxValue) for a in TTFont(FONT)["fvar"].axes]
print(f"Subset: {len(characters)} characters, {destination.stat().st_size:,} bytes; original: {FONT.stat().st_size:,} bytes")
